---
version: 2

references:
  images:
    middleman: &MIDDLEMAN_IMAGE hashicorp/middleman-hashicorp:0.3.44

  cache:
    rubygem: &RUBYGEM_CACHE_KEY static-site-gems-v1-{{ checksum "content/Gemfile.lock" }}

jobs:
  website-test:
    # docker:
    #   - image: circleci/ruby:2.3.3
    machine:
      image: ubuntu-1604:201903-01 
    steps:
      - checkout

      - run:
          name: gem and bundle install 
          command: |
            gem install bundler -v '1.17.3' --no-document
            bundle _1.17.3_ install --jobs=3 --retry=3

      - run:
          name: make sync
          command: make sync

      - run:
          name: make website-test
          command: make website-test

  deploy-website:
    docker:
      - image: *MIDDLEMAN_IMAGE
    steps:
      - checkout

      # pull and update git submodules
      - run: make sync

      # restores gem cache
      - restore_cache:
          key: *RUBYGEM_CACHE_KEY

      - run:
          name: install gems
          working_directory: content
          command: bundle check || bundle install --path vendor/bundle --retry=3

      # saves gem cache if we have changed the Gemfile
      - save_cache:
          key: *RUBYGEM_CACHE_KEY
          paths:
            - content/vendor/bundle

      - run:
          name: middleman build
          working_directory: content
          command: bundle exec middleman build

      - run:
          working_directory: content
          command: ./scripts/deploy.sh

workflows:
  version: 2
  website:
    jobs:
      # run on all branches and PR's
      - website-test 
      - deploy-website:
          context: static-sites
          filters:
            branches:
              only: master
